// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TbapID          int64  `protobuf:"varint,1,opt,name=TbapID,proto3" json:"TbapID,omitempty"`
	TbapName        string `protobuf:"bytes,2,opt,name=TbapName,proto3" json:"TbapName,omitempty"`
	TbapPrice       int32  `protobuf:"varint,3,opt,name=TbapPrice,proto3" json:"TbapPrice,omitempty"`
	TbapDescription string `protobuf:"bytes,4,opt,name=TbapDescription,proto3" json:"TbapDescription,omitempty"`
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductResponse) GetTbapID() int64 {
	if x != nil {
		return x.TbapID
	}
	return 0
}

func (x *ProductResponse) GetTbapName() string {
	if x != nil {
		return x.TbapName
	}
	return ""
}

func (x *ProductResponse) GetTbapPrice() int32 {
	if x != nil {
		return x.TbapPrice
	}
	return 0
}

func (x *ProductResponse) GetTbapDescription() string {
	if x != nil {
		return x.TbapDescription
	}
	return ""
}

type ProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TbapID int64 `protobuf:"varint,1,opt,name=TbapID,proto3" json:"TbapID,omitempty"`
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductRequest) GetTbapID() int64 {
	if x != nil {
		return x.TbapID
	}
	return 0
}

type TakeStockForATCkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QtyStock int64 `protobuf:"varint,2,opt,name=qtyStock,proto3" json:"qtyStock,omitempty"`
}

func (x *TakeStockForATCkRequest) Reset() {
	*x = TakeStockForATCkRequest{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeStockForATCkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeStockForATCkRequest) ProtoMessage() {}

func (x *TakeStockForATCkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeStockForATCkRequest.ProtoReflect.Descriptor instead.
func (*TakeStockForATCkRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *TakeStockForATCkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TakeStockForATCkRequest) GetQtyStock() int64 {
	if x != nil {
		return x.QtyStock
	}
	return 0
}

type TakeStockForATCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessTakeStock bool   `protobuf:"varint,1,opt,name=success_take_stock,json=successTakeStock,proto3" json:"success_take_stock,omitempty"`
	Id               int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ProductName      string `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Price            int64  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *TakeStockForATCResponse) Reset() {
	*x = TakeStockForATCResponse{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeStockForATCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeStockForATCResponse) ProtoMessage() {}

func (x *TakeStockForATCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeStockForATCResponse.ProtoReflect.Descriptor instead.
func (*TakeStockForATCResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *TakeStockForATCResponse) GetSuccessTakeStock() bool {
	if x != nil {
		return x.SuccessTakeStock
	}
	return false
}

func (x *TakeStockForATCResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TakeStockForATCResponse) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *TakeStockForATCResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_product_proto protoreflect.FileDescriptor

var file_product_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8d, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x62, 0x61, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x62, 0x61, 0x70, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x54,
	0x62, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54,
	0x62, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x62, 0x61, 0x70, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54, 0x62, 0x61, 0x70,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x54, 0x62, 0x61, 0x70, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x54, 0x62, 0x61, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x28, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x62, 0x61, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x54, 0x62, 0x61, 0x70, 0x49, 0x44, 0x22, 0x45, 0x0a, 0x17, 0x54, 0x61, 0x6b,
	0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x46, 0x6f, 0x72, 0x41, 0x54, 0x43, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x74, 0x79, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x74, 0x79, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x22, 0x90, 0x01, 0x0a, 0x17, 0x54, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x46, 0x6f,
	0x72, 0x41, 0x54, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x12,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x61, 0x6b, 0x65, 0x5f, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x32, 0x87, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x12, 0x45, 0x0a, 0x0f, 0x54, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x46, 0x6f, 0x72, 0x41, 0x54, 0x43, 0x12, 0x18, 0x2e, 0x54, 0x61, 0x6b, 0x65, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x46, 0x6f, 0x72, 0x41, 0x54, 0x43, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x54, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x46, 0x6f, 0x72,
	0x41, 0x54, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData = file_product_proto_rawDesc
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_product_proto_rawDescData)
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_product_proto_goTypes = []any{
	(*ProductResponse)(nil),         // 0: ProductResponse
	(*ProductRequest)(nil),          // 1: ProductRequest
	(*TakeStockForATCkRequest)(nil), // 2: TakeStockForATCkRequest
	(*TakeStockForATCResponse)(nil), // 3: TakeStockForATCResponse
}
var file_product_proto_depIdxs = []int32{
	2, // 0: ProductStock.TakeStockForATC:input_type -> TakeStockForATCkRequest
	1, // 1: ProductStock.ProductInfo:input_type -> ProductRequest
	3, // 2: ProductStock.TakeStockForATC:output_type -> TakeStockForATCResponse
	0, // 3: ProductStock.ProductInfo:output_type -> ProductResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_rawDesc = nil
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
