service:
  port: "9092"
  port-grpc: "1200"
database:
  postgres:
    user: "root"
    password: "secret"
    host: "localhost"
    port: 5432
    name: "amole_db"
    min-conn: 10
    max-conn: 100
    max-life-time: 12s
    keep-alive-interval: 20s
  redis:
    addr: "localhost:6379"
    password: "secure"
security:
  jwt:
    secret: "acret123-812xliasfekaltasfesa231"
    access-time: 1d
