// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TbAmoleMember struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Address  string `json:"address"`
}

type TbAmoleProduct struct {
	TbapID          int64       `json:"tbap_id"`
	TbapName        string      `json:"tbap_name"`
	TbapPrice       int32       `json:"tbap_price"`
	TbapDescription string      `json:"tbap_description"`
	TbapCreatedAt   pgtype.Date `json:"tbap_created_at"`
	TbapUpdatedAt   pgtype.Date `json:"tbap_updated_at"`
}
